---
- hosts: all
  remote_user: sysops
  roles:
    - role: 'ss-server'
      vars:
        ss_server_method: 'aes-256-cfb'
        ss_server_password: '1234567890'
        ss_server_ports:
          begin: 9000
          end: 9009
