---
- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install shadowsocks-libev
  apt:
    name: shadowsocks-libev
    state: present
  notify:
    - stop shadowsocks-libev
